server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: mysql.7285741627
    type: com.zaxxer.hikari.HikariDataSource



